# Variáveis de Compilação
CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c11 -g
# CFLAGS += -fsanitize=address -fsanitize=undefined

# Arquivos e Diretórios
ALVO = mini_sgbd
FONTES = main.c btree.c storage.c
OBJETOS = $(FONTES:.c=.o)

# Alvo Padrão (Compila o executável main)
all: $(ALVO)

$(ALVO): $(OBJETOS)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Alvo de Testes Unitários e Funcionais
test: CFLAGS += -DMODO_TESTE
test: clean $(OBJETOS)
	$(CC) $(CFLAGS) -o executor_testes $(OBJETOS)
	./executor_testes --unit

# Alvo de Teste de Estresse (Carga pesada para o relatório)
stress: CFLAGS += -DMODO_ESTRESSE
stress: clean $(OBJETOS)
	$(CC) $(CFLAGS) -o executor_estresse $(OBJETOS)
	./executor_estresse --stress

# Limpeza dos arquivos compilados
# Limpeza dos arquivos compilados (Ajustado para Windows)
clean:
	@if exist $(ALVO) del /f /q $(ALVO)
	@if exist executor_testes del /f /q executor_testes
	@if exist executor_estresse del /f /q executor_estresse
	@if exist *.o del /f /q *.o
	@if exist *.bin del /f /q *.bin
	
.PHONY: all test stress clean