CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c11 -g

# Nome do executável
TARGET = sgbd.exe

OBJS = main.o btree.o storage.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

main.o: main.c btree.h storage.h
	$(CC) $(CFLAGS) -c main.c

btree.o: btree.c btree.h storage.h
	$(CC) $(CFLAGS) -c btree.c

storage.o: storage.c storage.h
	$(CC) $(CFLAGS) -c storage.c

test: $(TARGET)
	@echo [!] Executando testes basicos de insercao e busca...
	@echo 2 inserir 10 inserir 20 buscar 10 status sair 4 | $(TARGET)

stress: $(TARGET)
	@echo [!] Executando teste de estresse (Benchmark 1M)...
	@echo 1 4 | $(TARGET)

clean:
	del /f /q *.o $(TARGET) *.db *.csv 2>nul || rm -f *.o $(TARGET) *.db *.csv